---
version: "3"

services:
  tap-the-button:
    build: .
    working_dir: /app/
    command: ["node", "/app/server.js"]
    ports:
      - 9200:9200
    volumes:
      - .:/app
    restart: unless-stopped
